### ISSUE TITLE
GLIBC_2.29 not found

### ISSUE THREAD

**Issue by ptarjan** [livegrep/livegrep.com#6]
I'm currently using your [livegrep/indexer](https://hub.docker.com/r/livegrep/indexer) at version `90508866c3` and it is working great. If I try to download the source code at `b974cd2c06` (and fix the one breaking you change you made of renaming the flag to `ignorelist`) and then the `codesearch` binary won't start with this message:

```
/livegrep/bin/codesearch: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /livegrep/bin/codesearch)
```

Can you publish an updated image with the changed dependency please?

**Comment by nelhage** [comment]
I just pushed 71e6f5bb46e93913b563d472505e56f02cd61ce0 which should build `livegrep/indexer:b974cd2c06-0` which will have the latest release and an Ubuntu 20.04 base which should fix the glibc version issue!

I really should merge this repo into livegrep.git and just push images on every push there.

**Comment by nelhage** [comment]
Ok, had to tweak the build, but the image should be there now. Let me know if it doesn't work.

**Comment by ptarjan** [comment]
Thank you! I'll go do the upgrade and let you know if it doesn't work.
